recommender:
  extraArgs:
    v: "4"
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      memory: 512Mi
  nodeSelector:
    node-class: homeserver
updater:
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      memory: 512Mi
  nodeSelector:
    node-class: homeserver
admissionController:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      memory: 256Mi
  nodeSelector:
    node-class: homeserver
