metrics:
  controllerManagerAddr: ":8080"
# Pin Controller to stable nodes
nodeSelector:
  node-class: homeserver
githubConfigSecret: arc-github-creds
resources:
  requests:
    cpu: 15m
    memory: 128Mi
  limits:
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
