nodeSelector:
  node-class: homeserver

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi

config:
  datasourceSecret:
    name: postgres-exporter-credentials
    key: DATA_SOURCE_NAME
  disableCollectorDatabase: false
  disableCollectorBgwriter: false
  disableDefaultMetrics: false
  disableSettingsMetrics: false
  extraArgs:
    - "--extend.query-path=/etc/postgres-exporter/kine-queries.yaml"

serviceMonitor:
  enabled: true
  interval: 30s
  labels:
    release: monitoring

extraVolumes:
  - name: kine-queries
    configMap:
      name: postgres-exporter-kine-queries

extraVolumeMounts:
  - name: kine-queries
    mountPath: /etc/postgres-exporter/kine-queries.yaml
    subPath: kine-queries.yaml
    readOnly: true
