apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: node-reachability
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: node-reachability
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: icmp
  interval: 30s
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        - 192.168.0.76  # rpi4b8g1
        - 192.168.0.77  # rpi4b8g2
        - 192.168.0.78  # rpi4b8g3
        - 192.168.0.79  # rpi4b8g4
        - 192.168.0.80  # rpi5b8g1
        - 192.168.0.81  # rpi5b16g1ssd
        - 192.168.0.82  # rpi5b16g2ssd
        - 192.168.0.83  # rpi5b16g3ssd
        - 192.168.0.84  # rpi5b16g4
        - 192.168.0.85  # rpi5b16g5
        - 192.168.0.86  # rpi5b16g6
        - 192.168.0.87  # homeserver
        - 192.168.0.88  # homeserver2
        - 192.168.0.89  # homeserver3
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nexus-health
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: nexus-health
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: http_patroni
  interval: 60s
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        - http://192.168.0.89:8081/service/rest/v1/status
      labels:
        component: nexus
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: pihole-health
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: pihole-health
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: http_patroni
  interval: 30s
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        - http://192.168.0.87:8080/admin/
        - http://192.168.0.88:8080/admin/
        - http://192.168.0.89:8080/admin/
      labels:
        component: pihole
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: vip-health
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: vip-health
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: icmp
  interval: 30s
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        - 192.168.0.248  # K3s LB VIP
        - 192.168.0.249  # K3s API VIP
        - 192.168.0.251  # Pi-hole DNS VIP
        - 192.168.0.252  # Edge Proxy (Caddy) VIP
        - 192.168.0.253  # Internal LB (HAProxy) VIP
      labels:
        component: vip
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: firefly-health
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: firefly-health
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: http_patroni
  interval: 60s
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        - http://192.168.0.88:8082/login
      labels:
        component: firefly
