nodeSelector:
  node-class: homeserver
resources:
  requests:
    cpu: 15m
    memory: 128Mi
  limits:
    memory: 128Mi
config:
  modules:
    icmp:
      prober: icmp
      timeout: 5s
    ssh_banner:
      prober: tcp
      tcp:
        query_response:
          - expect: "^SSH-2.0-"
    http_patroni:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        valid_status_codes: [200]
        method: GET
        preferred_ip_protocol: ip4

# single Probe CR instead of multiple ServiceMonitors
serviceMonitor:
  enabled: false
