nodeSelector:
  node-class: homeserver
resources:
  requests:
    cpu: 15m
    memory: 128Mi
  limits:
    memory: 128Mi
config:
  modules:
    icmp:
      prober: icmp
      timeout: 5s
    ssh_banner:
      prober: tcp
      tcp:
        query_response:
          - expect: "^SSH-2.0-"

# single Probe CR instead of multiple ServiceMonitors
serviceMonitor:
  enabled: false
