apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overwatchd-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
    notifications.argoproj.io/subscribe.on-sync-failed.webhook.discord-infra: ""
    notifications.argoproj.io/subscribe.on-health-degraded.webhook.discord-infra: ""
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: infra-base
  sources:
    - chart: overwatchd
      repoURL: https://nexus.gillouche.homelab/repository/helm-hosted/
      targetRevision: 0.0.0-latest
      helm:
        valueFiles:
          - $values/resources/overwatchd-test/values.yaml
    - repoURL: https://github.com/gillouche/home-cluster-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: overwatchd-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
