apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overwatchd-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
    notifications.argoproj.io/subscribe.on-sync-failed.webhook.discord-infra: ""
    notifications.argoproj.io/subscribe.on-health-degraded.webhook.discord-infra: ""
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: infra-base
  source:
    chart: overwatchd
    repoURL: https://nexus.gillouche.homelab/repository/helm-hosted/
    targetRevision: 0.0.0-latest
    helm:
      values: |
        image:
          registry: nexus.gillouche.homelab/docker-hosted
          repository: overwatchd
          tag: latest
          pullPolicy: Always
        config:
          argocdURL: "https://argocd.k3s.gillouche.homelab"
          argocdInsecure: "true"
          guildID: "1459504241080008737"
          allowedUserIDs: "192318521311625218"
          allowedChannelIDs: "1477640456090423348"
        secrets:
          existingSecret: overwatchd-test-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: overwatchd-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
