apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overwatchd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
    notifications.argoproj.io/subscribe.on-sync-failed.webhook.discord-infra: ""
    notifications.argoproj.io/subscribe.on-health-degraded.webhook.discord-infra: ""
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: infra-base
  sources:
    - chart: overwatchd
      repoURL: https://nexus.gillouche.homelab/repository/helm-hosted/
      targetRevision: 0.0.1
      helm:
        valueFiles:
          - $values/resources/overwatchd/values.yaml
    - repoURL: https://github.com/gillouche/home-cluster-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: overwatchd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
