defaultSettings:
  defaultDataPath: "/mnt/ssd_nvme"
  replicaSoftAntiAffinity: false
  replicaZoneSoftAntiAffinity: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  concurrentReplicaRebuildPerNodeLimit: 2
  replicaRebuildingBandwidthLimit: "120000000"
  guaranteedInstanceManagerCPU:
    v1: "0"
    v2: "0"
  replicaReplenishmentWaitInterval: 600
  defaultDataLocality: best-effort
  replicaAutoBalance: best-effort
  createDefaultDiskLabeledNodes: false
  storageReservedPercentageForDefaultDisk: 20
  storageOverProvisioningPercentage: 200
  orphanResourceAutoDeletion: "replica-data;instance"
  orphanResourceAutoDeletionGracePeriod: 300
  offlineReplicaRebuilding: false
  defaultBackupBlockSize: 2
longhornManager:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 1Gi
  affinity: {}

longhornDriver:
  resources:
    requests:
      cpu: 15m
      memory: 128Mi
    limits:
      memory: 192Mi

longhornUI:
  resources:
    requests:
      cpu: 15m
      memory: 128Mi
    limits:
      memory: 192Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-class
                operator: In
                values: ["homeserver"]

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  defaultAllowVolumeExpansion: true
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring
service:
  ui:
    type: ClusterIP
ingress:
  enabled: false
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: security-authelia@kubernetescrd
