apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    notifications.argoproj.io/subscribe.on-sync-failed.webhook.discord-infra: ""
    notifications.argoproj.io/subscribe.on-health-degraded.webhook.discord-infra: ""
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: infra-ci
  sources:
    - chart: sonarqube
      repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      targetRevision: 10.8.1
      helm:
        valueFiles:
          - $values/resources/sonarqube/values.yaml
    - repoURL: https://github.com/gillouche/home-cluster-gitops.git
      targetRevision: HEAD
      path: resources/sonarqube
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
