---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-exporter-credentials
  namespace: secrets
spec:
  encryptedData:
    DATA_SOURCE_NAME: AgAuxuqDSInlaagEk1THSmAIJeqWpO6Lmt3H6aucNDS98qa/eyABXzxTeBSrKrpSrekEuyTO4aST/RsAgXSZtXs1sAFh7tyake6ViE0ReKyvrg1x9xl4zdyshUQ6dVPAsigQeWlABdAW2uab/45NeBbfLfpF9hwWNCaqW1U9Ip9MbzMLRfu0FiBGJc3KVao+Vw4coJdljVOqnfWsZtV9ku7BbwdHA7SEA+hjAUV+TjEO4jU6pgfwdCDvBW987bkoG8b9Xb5mf17PK4bSAJ3D8oDhac8C7v0OVHtP94zjPpDT/H+cJOcnDcGBCMFuTFGEPjYyyCE+DjA89wYCtgPsb9+AKDITSk1MP422AJTCP6v5+9NS9H9JbdFp6CKK6wiufaMU9it+J1SHB+eXXJsqheeFv1HO9lWX9SZsFvpBbfgrjbaQWJRFO5VyLyyHKeWXXE8BGC08Y1JPEqL5lpdKZhXOkdzgN31DJmboPkj1CC9ODyEGnDQ2qCpRgYfr4BsSLCk2auBOy4DpAL1BPNz4SGQUhRmUViqvsJsrABVuBs4RSYydvezREfJ7mf66/wSwfU6gHStSpcvLhLMDzEhpodEDGqVLdWshSZMwKsg9W72uk93n5lfi9tzquhK5YqUdf36HJZKpzjcaxkTnDdoqLW2TMZSD07yY9FPHPq4e3DlhzoY/m6KyqTEntrO65Gl4KoUqThHA6B28C4YDo3O6kYqNOyTZQnqdKl59+2dGJcIFHpm0Q8Oy9R0aEyjbtKrIGm0ASUhrqcEQ5LIkVJ9fgcEcb0J8uHz2hph/6i44hZ8mtnIyHVhMClI=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: postgres-exporter-credentials
      namespace: secrets
    type: Opaque
