---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overwatchd-test-secret
  namespace: secrets
spec:
  encryptedData:
    ARGOCD_TOKEN: AgAQ0+PIePgjxUCsElLGJwqaQd0xlNjv55nOLCH6pyLZxPX6UqzXVbcHch/WcYwkDOvn6Hbk3FEXNN0NxOkqKe+R2FkpjIrhtukiBxiX/XoqeeldJnGNrDGuUoAwkQKsk+5noSDyx+nMg2uem1y9ylfbh+/4jbbunaPSQMUSlHtGg90UFdmXwvD7mLEjJt8E4gyEqK+CvjF4iD4njiMTxoFk7l4DAWEggKxbYYZVICG8Ztjag/qo83265tfF2ueGokRDlWXw4K/x6w461CGnuL5SvAZKBp9JInFhaItZWbXW095bsUfh00UdsmIaxR3ZWvFYmtl37p7p4Yo5iLb5e3OJIs1NgPLOoLFD1HZVKovVHRIQzYiYHE10GyCtP/+ygT4blxfgXdQMdwRmZAbTIH6J6pxz9MV7y/LNs3mTMyvlU4VGGO33avsF4+jurD17O2BzPOIaZ6qae27TFuhKnXeyIYFsDxdpIeFtZx2Y0B0Mhe3AQ/bWwyo6YNM7Ja4nZBLJsYVTWfNdP3i1HEUvN+lX0Duzu8j1ZKt7e3ph7q0FlFlB3fMalWvY/teCfRhmWN6qZjgN6CUg3AZsWQ4TkWkC1xM80gMQsKYhZ8B+tudKE26jtlh/QCmuM6GQ2IOdLS1qkp02p8VjeVK0+gbDyzggbGYO66+LGgZPnj03yhB47Fdh//IIXrj9WC8aukldZeZNXzkAfGxTZkz31UvNOftPFXBcGVWtPjYSDxg2fIHLpcm1vLOGKtmJkna3mjVx2pTBLDCcV0XxWtEAvB9MU4Thmn4adPBgG3UdNQ49CMcNFj/TiFvBm4kyeBBMjjAwLIbbSU6xnbeoQFS5SffAb2WyVsi2lVZ+PGqY5Q692ctoKbkY30HtRJPZ+7wUO/QZP32ro+yfso/3IjGdY6+hcnu1C0mNGLSDnzY3Y06Eyb0cMtVpXSj33QEj2nnj+iOmHRVAc84QkS76bRaUJFhXP5CQgtdSbfEL/wuzrxUaaCcpeIl6aZRKinsByqSrtg+A040g+E8=
    DISCORD_TOKEN: AgB9UNbzCLvGrqVKH7ATYlzcZ5rZgIlUk5khwwMTnB2BsiJRalWRRi6f6T0H7rflH7xP3VZvQuhhzWEi1AFbQgZ+My76vLYNsR45i5MN6GOVnlyJCcuEOA/IBto8Wp4Hw8rxIY3JAHRrbLfWKIIUtGF+vL1okFcaJC/QA62NQBz9weA1yYkzhNXNsDr4eNyXejk118i5tQXCm3b04l72WH3b4vwRaZFmxnLNsfYX6FGSsBS9s/478JEGl+XGLnN3h8nwZL3WQeElCDZVgUZKlFPmqgy37/PGVuDJ2duM0yirtmxxleS+xyrOvm37X6fMaidm7b3l4jvaY/I9mSJtss8L+rWvF2WqgaoiW+lV6vlPbQp+p2UqCP60GmOCVfgJhsGk1+S8HflItTMmDGc2fovDcaCPZjptqzNIAIU6oIrxbq65Nx2SN4QejHQuzNbmKCpqv0ie3J5ZBGCbC4RxBmZG2AGEmiRuGPrvt02UfmwJ1t1qnrDbFeVj8JUNEfZpMCxaR+K/wS69/z2pDfgDZ5o36XAE2/cWTFgjj8hSHzOgmmgiPNs2EZ3nZEt5e9QY0n3/OX3ZoSDY0O2nFuWYiZYMBOe5kfe1yS7GLjEdmoPfb0p5LbpZ6ijUcFhdvAtKk0N14vV1EjRULjJmX/C/2igYUWaAlNJ8B3gcsr2uDy+oCM5KHpBM6Yp1Hi4CgaBBPmncnKhZ1Rc7c0fEIYfC2nngCtf9677ikBopH08qpgevyy/JWvWhP249vC7ZvgzfxRaWqb6JZiOKoou91gClNctBmTvzkreQ/pk=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: overwatchd-test
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: overwatchd-test-secret
      namespace: secrets
    type: Opaque
