---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overwatchd-secret
  namespace: secrets
spec:
  encryptedData:
    ARGOCD_TOKEN: AgAzFxnmxxwWI6y7tWCNZwQOUgWhub80lcTwW0fCCO8rq0haWcKnV1SeW1ZpuPAPMxNbmaYf0UB+oGdoop+zM7X8PRJqtUxewuY7rFCAJI9xc70/OkrHzVKaRYuSuKCeDknnbPYGxnEnYig41c+Lm6gwycWs34VEOXJgnHU5tVdnRM8+whx12hJX6JtEiFhJZaOIL2i8J5mup5dqHTA0UHEgiY/+gdPUcNdic50J4Yt37o44it914UKBN36FScpbNxhrpV8BuH+C6fySv9UwidzP4G/Z4lWIh5ZTu4vxkZ/AafGqeO9AGKEvw1OWfgdGmgtarTpdkTiQQleH3I5ojjnEPnuDRKYfB9E0+0T1raU2Kb/QNLbpP1xknEasYelG53HDi28YUfEtGM1fNIhfdh0h2ZQP7k4XSdHbO6u3XgKtGLlrw8vb/yPCZZrwGFlujlzH2/fufpos+qzy/hkDIF141ZuuH99Djqx85zyWPCodobiQlOfYRvaQ+78Aj+HoCZF5yVQW58wJvtw2Mvln1ZHJMl/jTz6RNoqXBc1hD7LdefzitCfVNcmvo17Bvxp3jgFXUTPoE+QN2OL94DSU78MmsYHll75EDKHO4f91sx4gZnfxISnh2KkUSq3CEtJD0RxYONAkX9uz9bX7csuHmk+/itaR9ST1T2CW35IjHvPtITvff9PREWldbD/nLQgEX10cZ0dMHzbzKDCSethXfNjMqUnfL0/zPQD/E1gTS55yuWhsfQjTVGmNyP86o3kP3xYI6oYmhhFNEMZCpIGNYgxbdOv4H2z8dJ5IttsbhD8CkCUv9nlOsgkqS32Ac0Rt/AvmNaBJu5xViJt6R1mI8Lxkhenkbg8eFzE4QwGzJ2AMHnphBBW94k9I72Q7twvkNd+qefb2TTzD0cv7ZednC0nPqmhX5pfF1RYZ2nmYSLdVnRJIX6+REbHC4F+NQcTWXck7qU65n/U4FW3v7hROsKPlthMAzQ/7ijrNnRooQiS2FkxlOAYVhv7omm+3+nn6CjDXwkE=
    DISCORD_TOKEN: AgBLIPdjb1vpgwO05mVyzKxgsCV7gX0W26giRHgCPAAX4Mt/0LYdZxUMBwCBHim9NqorNzyPhhQZktcl1cNq7Gq1xAdu0eNVek58dTdwTYKYNDPqV0MNE56yHphiloTMQOwqYOMk/XKs4Ffqfck2aNblsMfog24z+VAfweZ1w9SuxvjjGLfN7m+WgjmlE3HqXqvsPcLOOuLp+2GNd19dfoDf5XNWGFPcDb2Kugxtrps4OvXoo6r92uzAkq5gZhIKgifJ3T0ShOSqvhCCtaT9TD7YnoUxam1Pv0Ud+h2Qx843F1q5JfnhjOmX+5WcvkjEOZtKuKnpgrZ+lLAOqQa+AT+hRNqXzoqeJUiAV5mf3dsjJiVv6b6IgHoVY6lGKpfSYVspW0lmG2g+VyoZtodsYiKOvVjWg7frqkWucRhcbTHClcnJNbNFpoJ/WXzol6E0mN1KmK7n3Y/5bQkdO0dB6IHDzfJUBEzKPwpExrvbSOlJvRRCaLRoKthQY/JBwQp5P2HjMTWwoFvuCnEALCOpcwxGyu8MkkygsBCq4PVYgngrU8vFE9dMbuUuC+4A9q807sk7jD3AQmEx+sqJS1bsTw+KVTWRDDFQZeYjloWRBuc0jpJTF9qAmCS02nyQvoBiIWVGJOUu2hBsev0F2Vb/RkcrcCxOgS/SsnoAxITxUdlfDYXjMzBvs8ylQD0bY/1YVWvgzvU27BbpedzL5ZYK5DzJ98u+ilebLyJSmOa9WFgajtcMU+zFF0Non802CmfWWkXho1vFU0P0w7QEhltBsOuveENGHZjjZvU=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: overwatchd
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: overwatchd-secret
      namespace: secrets
    type: Opaque
