---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overwatchd-dev-secret
  namespace: secrets
spec:
  encryptedData:
    ARGOCD_TOKEN: AgCcaAasa+XQ7nYbszYeFARd/G8npBUj5CXfE14W6H3O8orX8p3QV7xR3o4p6nlckEWH4nq5KH8R7gaY1noWJe3YpGLPFy/T5i6j0W59WlApqZaMhUan9+EC3nFyEx6d36KWo6MCjo4G9HUm8C32yh8FgAjjBa3lzEPqZbs4pojL+WTJYwTv2Gkqmf1aIvAaJfHLKkTyW24xYBoSwpZ/axrBPp/iIqihSW93V41hAL5HMzfPqoW9zeUgbzJYjcFvWUaEjJrkJNPt1Bs0dyrIovUoAagVlL5/Ot/66rV3w1ArsuAUXzB6glVQ1Ht4TQ6gGUa3IP6F7ev+CTzE0YO1MSidY0fH9kF5dTh4vri6mqAD3/JfE29+dMZZ5JpBWCJ0ZH38z1QwBOmXKGnmf0Z1VECiO8D+1Ix+K3V2ahD+GoElR3DWPubZ/pAGyEPumh/+hiNqRyOdO/ClTfY3uCkAYeTPTbdUB4rI1flGbXLpDZlI56PzgFB1AvpU4WxpaGHKQSgFRJgQL/ztyzMUN2HF9Zv9L3+ZblVIELqEeqKTB3uNZ2uBWbZ6nPkZiSf2dKIK0vLtiBmSrKrmI/P26+jioH8RZpehUg0g7eM/GY7pciQYfswHsViq2z+0/2yiq3lU9rDsXwTPKTPf2aGgAsMg1s06/1hTqDn7et1kT52khrDX51XiIlX2XrU7JxeuaUFBmW1rsKFPK4VYmtfhg02VHKJQa+QgD+8LjmDlndtNh8aMtXcR99VhHHXqo016y6/AQReZtrwPK8UC04Y4t+LRbZuhuVujD+fyEXs2YgpOFvMtliLuaKIoCcdtjprmURCygO6SLf/CsaQKjQSPUrom+1WqGhJB8YvqIpTrfw0SZOKiHQqajWjEWvKhJ0xu0ZHX9baY11Vi04tdyrxzfInTAK7cpUy3yuBDwUf8DCzoGwQyF83ZHK9VADF6uKjAGOdieP/7FsTHbeWb0W50a+94IKjIgL7pptdoo/bR/fanOAOLH5N1ElVegiH3Cvbrqoo5R6ilgog=
    DISCORD_TOKEN: AgB0AH/PxXRSnBn6n2R9AtloMBwSvClVDHf22aA9XGaZk7K7iWnTBKxYj1PMovWmDnVqqvIMddSpzUUOpTHod0nxyRLVVSH6yftPuGn6RN1W1umYicyp+rb61uKqy3/M9yS6Cjbj/3f83slIhY0DVXmmQpH3Bc6Of5NC+fGde+jv7SOaW7StK3JS/ga2gU9ZYxjUSr9FJ0SMxCz8H4A8Y//ybWv0qzLV702zmVsTLaBJhg4v/JPuKrWqtZ9H6sb3hY3rd+sgc33fQ60gcmCCT+KAUSXvevVh26kKcjvmrNxZkT4D37W3hjcxILubK0C9L2Gl54tLWmV6Sr2VMbsZz2XEyHkMWafApZ6ulq9+zj65TlY1RDMtcq2rFsrpVGC+5fWZxhjd3XydA7nZxQVSTDa+19vGGl3zGxEQtAwSWYYrBD4xfFkfM2OQAPKYpivKzQnBUL7p2xcBdC/6huAKVPee5Jf2FbRwHY3ytQTceG87br/krB8F2l7+7G/YensRbEnIzmj5ePwDgPfvUjWSjW1wDx/cSC/OR/vtelVVN0duRdU8GMWXjz5lOutCLCLENAyRoJ+VtNzor3MDZqYod/Ynkyc5AaKPNLsHqmZaNPWLZ9U1SEtV0YeFOXh/pImQfcw+xcJHnCEFinMeDQri/fmTclR8Crh5WuyUxtwXbg+9z40py6hJ80mLblREgnAZv5uFwNHGSkBsD302o6px+iyickV7yoYOs9pusZZR5xkQ0oUHUpui92AYZBM49H4V7Puts5HveqQekD7b2jOzQhftexEl07gFs5g=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: overwatchd-dev
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: overwatchd-dev-secret
      namespace: secrets
    type: Opaque
