---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-rebalancer-discord-webhook
  namespace: secrets
spec:
  encryptedData:
    storage-issues: AgCkFJjAZJ2kKYakH0xeM7Gaky8MoVf82dXCmFqnPVgyaj8+BlGYOF2nssBx5z9GIUhjNXDtDSPpO3KRtAFzrFZqFzzscDOkRsdFJ2G9+P7E7KluNxasHe+5BDb3peCAtscO0QaARu0j7BBDAX5ejJ2Q1If+dRey7Juo9b63WE8jMqszJklC2u0nHtOoMRVZEgeD4OoWZMCxK0/b/Cr2jtvTe3n2wYWlITkD9XpWyNT3CZszhD+PYNDgKQ2PfZ4oQf+w5S/xF2jSCIK9wriL/H4xINYdP7MzgcQv4PL0CqP2VVqw8tNDeL8bybb+O7JykHEIqw23n2aw41sJ3DTyKMjHIoTOqa0ApOnOQwSy/QcmkQdfqa9nfpfEk056c3pBYpvbgDzTGdLTnVw8vp1S7ZAsjI9k9A6E8bJ5O7ah1EB4C5qClk6NnP2iuLI5AqnaqYL+wLUGVJ9pTtxo3Feewv0e07eOT4cti8K+q403P9jNExWf5RWs+KwchhxBiTwriw3EW9OvuWl+YVA0i9vPNnLPr+JwzXoqjfY0DTfrlzjHvj8QXv5HtllO6mfObQHzpudzwhdPv5ywftjqTHSIYg1qVw+NxJ4OeBYVytJNmSblJDUV5F5XsZ/sCnHugnM6YcFvxP1obEkxQbNQO9nShuodxT5nqCB23W2wFqLheNNbhudlMfe0cHze0Br3qmfR7mJ2kJh6qbywCMdKWxhHmBnMTyWF4GnE6C5eeU/f9JjBJrP8Ok+/7eub/884pczpxFNce+kp2WKScQTxABIJ2nCR263ix3xiDjtOOdZzL++b4q8tcMyYTfM5fkKCA17tle5N+2bqfm/MndzwLdboXIA9pEC5BpX7mViu
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: longhorn-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: longhorn-rebalancer-discord-webhook
      namespace: secrets
    type: Opaque
