---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shared-db-authelia
  namespace: secrets
spec:
  encryptedData:
    password: AgCGwzhkJiSJZuC+rcYF5rSB36wkBudslXQEQ6XsL+UZuX2hBxU2SiC7wVaEPEYYlCmrU6h1O4+V1oEUeM8DPaFY95vBerbYC3ijZz1NXSuo4rG/DvCUekgrDIbjNUD5+OF6ts3RIqlTWYYwHoblQXcYMm19red8A6R8Nd46OJCAzqaycCZpPBgG9hkKUtb4TOkGCcekpflXS63+SysAhojWU/DUjbQ/Td2E/ZBhKXeHxONdlzXeEvQg11gvN+L5f98F18FjtPH4WXRf1C87VyU2Py3WwLOylcHr4B3TMhd+tSM9dDDYNIuLrIBv4lhAHYoAzSTkfkqm+QRMEo9dOJvmeqDIFbp963GfGx1quhsmVpQpAiE/v5DqDHCrQfpHfaSZfnXPTWcAeMqUZhyFK3J2BZlESx3c/cMTRUxn5b+VZvk9kvyZ9dSSn2k1OZsZpFfYWCbXDMrYeMkS/5bcYWbblVrh//YM6s1Cs6qZdKMafqWimOBaUm1FPAqC7LeWQquPwZZmoTeubuwGU2fdky+JLCrQ2t7Xd6/FdgFs/e5vHUzt+s6S5PlTA78Yrx3v0AyPP7LmFA2rWkm+ox2WG62ZW89XWHhryIDBH5CJblpp29mrJN4MZc22RIZtNyDjMO97SR3zBwAIyHkqEu/YAj2W5Di1mHOzm5ckSKAs56djkzk6Gg4sgEM8x+wb3MmY3tPmPhDQPX/XF3UMiU5v187beCUo8RcNwJllbVVIwhkCArP2JQBWug==
    username: AgCGDjT8zXIqPpmqOxfWWK1EZ5sD53LKx6L2EQ4yWgiI/0NGpOEVDPYiSTv1InBXGLJ0klFb998/mLVVbcmETYbj3fMU9VkfVbVEdisEK+z8AvlInKEpQCyHGVidKpw04FDgf9Kdn7Ka812ZfntlN+XWSVEtLO3E46kWwkG6bMdjMIkYEDDXlj1/PWtZ4xkHZeK62LNN9d3IP9JSBX9MACPq+fCqooMJ0DdYbIRuAAUC8KP7NeFbjaImUBfmNlYdDwo035Cqf7mmFnDJxHqWm0DgVTGP/qu3CW5/q+9fc00hGRWGR8JTAnxK9jfKHLZy5uR4pFN2HFqtw/Eik+N9AlN0G4tc9zG9UWzaT8VXzLVuY/vKx3YMJ7lilGX7UHtJX6vbMsdvTBlzDbHkF3rkFzr+EZmiV0TVo6H9ZO65lln6Byx2pAZKhgXtKB6lOnGXVNtksnYaaG986ndgAKB1Mjmnp0WqzK20U3bsLYvFgtQtMI8260sjF1uae9mNwpRgjjT5ESU+kavitQeIqHzhdRgvlRVN8jZzReapeXOOgxxzw0/pjveE9foA8ilPPhRqO7l09Vo2kZ1j8vUgzGhsj4Pxgb5wRNXC2l7F1mm5HABFSACndlqlU9vo4ht8LjhNQI3F+mxUHJFssccBwTDSZ7tPluJQKj1UpjVwfV/UrlucoIPa2Mglwll5vpzaPbtexYlxwaxUP47PuA==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: shared-db-authelia
      namespace: secrets
    type: kubernetes.io/basic-auth
