---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overwatchd-secret
  namespace: secrets
spec:
  encryptedData:
    ARGOCD_TOKEN: AgAjaLJYQjLPlmd5WglP0VMeyPCOv69DiY/IJUrptYx/1Cco54tiBOj+D3t81JAcs1NZ/Zj/a4x+6zkNxuv2QgjNrQ1/2huARvXRBkeLBczDb38uvRvVbnxYBsVF6vyUkdE0slJ9wTsHcgBG3bRgkZvRX0nPqV1LzRo6ulNWFzw0XM++zrB0uTCnyuko8++EG44B6fjcYdX2oZORaIR/r43OsgoX6HrHXStM8Dqj1gz5B50WSgKPYWI7c1cUO1R3b86ie2IwmVBzZwgx7meFlm7eCgBIPukewdz43jVTNSOQucjHOdpBYRwOdfqXzV47VpDvMu+q/sZ04U1yC+1Y0USLHJkBg9dxlTOy/636lh8c9JzS2I1HNva/xThm8I1zFRqqIOSupd0SrmT2DR4CAyh4yFCk89vRLSo94diBirQnA5VmoJVtvEc/s0KyNbM+0mkFdD9+YITtq6jdGYWmByqYn9IZsbae3AOpNAjdbedqh8ewK8e0b+rd28JYzvDJ5HR4LJuyAHG/zDdjui8j/AYBsaqwcn6W6qLUguPj/w8YDjSO+4tqRwJapuvFv852vRHamcyzp6KK1/97z9EgO9O4xK7qL1lsEnOoWEyD95Vqs3XccL5aRUw9w9mGZKPQLpG+6WTF0+tYSw7vABL4VybCsOyLSajUmhhLpfKvF1o0hulYIIqFdbXYH+INTGlQIN3Ke3ROcwNmIHoKNfu2D2cyF4KzipKHFzqAN0JrkIhyFNUfB7tjVu5QFdmra/jr9ymU0zp0Yd35iGrk3JSN+WPoEdnBPJK2ToQNTqvzX9OK9/ZOMn5RIW4O+o4kGOIcf8lzHSvWbUSMs3Q7sokb/DKqVE92RQ1BJpPILGd+NuAr8cm8nA0jJmMlGPXEYGyFaxipfnl3X4w9YvK643ja0NduBcrngWYZ+0I4hiEsWu8s6mArptmEG1l8gAIep22XWnrlJ85F7wE3rQethwMQLYikiSDptI5OnAnhYQCUQIhbaTzwN8SiTAYDgTAjep5CUGvOT5w=
    DISCORD_TOKEN: AgCKscX+HYNAJuvEcTXyG6oO20KyRFs5qVz8q16ZuMJDSuevfs6tdeKE65rg24ZhPK6HNG3SnPBnwYUOiDlVb/CKEr2W2CEbIS9Nr/EIyW0+eA5x+KDhYxQ0w+46zYv66DelsIOIRoWf+kXQouB2z3QDdnaO64IlPz+GIB5NYY8Rpfl5ld7OKQrH102P/AACZD1Y/CklztlGdR/RZWImKvDhl8ywrB+wuLN/CBkLvZjug49yzD5bCQQr5qAZl0ZCzbGRPX6YbkBPLIp0a4fcqRwZ6ULjIZhJQIhUZMsbKjhSyR6K8+sbbXhHrrXzBpGlPjc0E5pahVrcaU805YNoSwVudMT2XfYcb7Fl/qnDpdmNr7CBfDI+JFyUdi6dxtCmKbAiSb5tHhX/FxXg0lJYBYzabd0uo+oHPEhCmn8KjqwB0zQ25KI1GW/JLdIm3YBzNu4nq/ckDgN4yJaTYzYj26sUL09agjXSwCF4MmdHi6pQX5kPhyaOwkBi3PyRU3dLVUeRi9N0pPBnlZ6qKC7IIdLxqyRzhTeWIGvownh+PBmJzhGSyfDauz9g7GmNIfE4B23dtxHqMQZQ7zM57irS6Lf97WLJ9EBsmpth9RnBJFp8myO8kdQPU5PFlCxi0QUMcqtEZRtxXNQXvi5NIrZJFtnPaTk3XS56OOgApopZ1Vjy3GyIHD/GOx92Rqq8gfbDnpnkbHHLwDrJVphX3sFIifqc48ZBr2UxdyNk/BTAUP/xHZtQ9omEyUqpIyRyeMznJhf/BX13pueWEaX+6lbXVxjmVtXAWKT3+Bo=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: overwatchd
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: overwatchd-secret
      namespace: secrets
    type: Opaque
