node_selector_enabled: true
nodeSelector:
  kubernetes.io/accelerator: amd
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
securityContext:
  privileged: true
  allowPrivilegeEscalation: true
