apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: seaweedfs-s3
  namespace: seaweedfs
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: s3
