replicas: 2
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
auditInterval: 60
validatingWebhookConfiguration:
  failurePolicy: Ignore
mutatingWebhookConfiguration:
  failurePolicy: Ignore
controllerManager:
  resources:
    requests:
      cpu: 15m
      memory: 256Mi
    limits:
      memory: 768Mi
  nodeSelector:
    node-class: homeserver
audit:
  resources:
    requests:
      cpu: 15m
      memory: 256Mi
    limits:
      memory: 768Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-class
                operator: In
                values: ["homeserver"]
